/**
 * The validation rules in API_SPEC.md §9.
 *
 * Postgres cannot check JSONB shape (DATA_MODEL §4), so this layer is the only
 * place these hold.
 */
import { invalid } from './errors.ts';
import type { ErrorDetail } from './errors.ts';
import type { NoteResult } from './scoring.ts';

const BANDS = new Set(['green', 'amber', 'red', 'missed']);

export interface TargetNote { midi: number; startMs: number; durationMs: number }

export interface AttemptBody {
  id: string;
  exerciseId: string;
  instrumentId: string;
  startedAt: string;
  durationMs: number;
  engineVersion: string;
  inputSource: 'audio' | 'midi';
  rhythmScored: boolean;
  lessonId?: string;
  noteResults: { version: number; results: NoteResult[] };
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function parseAttempt(body: unknown): AttemptBody {
  const d: ErrorDetail[] = [];
  const b = (body ?? {}) as Record<string, unknown>;
  const need = (path: string, ok: boolean, message: string) => { if (!ok) d.push({ path, message }); };

  need('id', typeof b.id === 'string' && UUID.test(b.id), 'must be a UUID, generated by the client');
  need('exerciseId', typeof b.exerciseId === 'string' && UUID.test(b.exerciseId), 'must be a UUID');
  need('instrumentId', typeof b.instrumentId === 'string' && b.instrumentId.length > 0, 'is required');
  need('durationMs', typeof b.durationMs === 'number' && b.durationMs > 0 && b.durationMs < 3_600_000,
       'must be positive and under one hour');
  // Required, never defaulted: an attempt whose engine is unknown cannot be
  // honestly compared with any other (DATA_MODEL §3.6).
  need('engineVersion', typeof b.engineVersion === 'string' && b.engineVersion.length > 0,
       'is required — an attempt with an unknown engine cannot be compared');
  need('inputSource', b.inputSource === 'audio' || b.inputSource === 'midi',
       'must be "audio" or "midi"');
  need('rhythmScored', typeof b.rhythmScored === 'boolean', 'is required');
  if (b.lessonId !== undefined) {
    need('lessonId', typeof b.lessonId === 'string' && UUID.test(b.lessonId), 'must be a UUID when present');
  }

  const startedAt = typeof b.startedAt === 'string' ? Date.parse(b.startedAt) : NaN;
  need('startedAt', Number.isFinite(startedAt), 'must be an ISO 8601 timestamp');
  if (Number.isFinite(startedAt)) {
    // One minute of tolerance for clock skew.
    need('startedAt', startedAt <= Date.now() + 60_000, 'is more than a minute in the future');
  }

  const nr = b.noteResults as { version?: unknown; results?: unknown } | undefined;
  need('noteResults.version', nr?.version === 1, 'must be 1');
  need('noteResults.results', Array.isArray(nr?.results) && nr.results.length > 0, 'must be non-empty');

  if (d.length > 0) throw invalid('Attempt body is not valid', d);
  return body as AttemptBody;
}

/**
 * Checks the results against the exercise they claim to be for. A mismatch
 * means the client scored against a different or stale exercise, and storing it
 * would produce a scorecard that disagrees with its own exercise.
 */
export function validateResults(
  results: NoteResult[],
  notes: TargetNote[],
  rhythmScored: boolean,
): void {
  const d: ErrorDetail[] = [];
  const seen = new Set<number>();

  results.forEach((r, i) => {
    const at = (field: string) => `results[${i}].${field}`;

    if (!Number.isInteger(r.index) || r.index < 0 || r.index >= notes.length) {
      d.push({ path: at('index'), message: `index ${r.index} is outside the exercise's ${notes.length} notes` });
      return;
    }
    if (seen.has(r.index)) d.push({ path: at('index'), message: `duplicate index ${r.index}` });
    seen.add(r.index);

    if (r.targetMidi !== notes[r.index].midi) {
      d.push({ path: at('targetMidi'), message:
        `expected ${notes[r.index].midi} at index ${r.index}, got ${r.targetMidi} — results are for a different exercise` });
    }
    if (typeof r.coverage !== 'number' || r.coverage < 0 || r.coverage > 1) {
      d.push({ path: at('coverage'), message: 'must be between 0 and 1' });
    }
    if ((r.centsOff === null) !== (r.detectedHz === null)) {
      d.push({ path: at('centsOff'), message: 'must be null exactly when detectedHz is null' });
    }
    if (!rhythmScored && r.msOff !== null) {
      d.push({ path: at('msOff'), message: 'must be null when rhythmScored is false' });
    }
    if (!BANDS.has(r.band)) {
      d.push({ path: at('band'), message: 'must be green, amber, red or missed' });
    }
  });

  if (d.length > 0) throw invalid('note_results is not consistent with the exercise', d);
}
